sparrote/notes/models.py
from sparrote import db
from sparrote.users.models import User
from sqlalchemy.orm import validates

import datetime

from collections import OrderedDict

ERROR_MSG = 'Empty fields are not allowed'

def dump_datetime(value):
    """
    Deserialize datetime object into string form for JSON processing.
    
    """
    if value is None:
        return None
    
    if value.strftime('%Y') == '2016':
        dateformat = value.strftime('%b-%-m')
    else:
        dateformat = value.strftime('%Y-%b-%-m')
    
    timeformat = value.strftime('%-H:%-M %p')    
    return dateformat + ' ' + timeformat
        
class Note(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    postnote = db.Column(db.String(500))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    datetime = db.Column(db.DateTime)
    
    myuser = db.relationship('User', back_populates='mynotes') 
    mytags = db.relationship('Tag', back_populates='mytagnote', cascade='save-update, merge, delete')
      
    def __init__(self, postnote, myuser):
        self.postnote = postnote
        self.myuser = myuser
        self.datetime = datetime.datetime.utcnow()

    @validates('postnote')
    def validate_postnote(self, key, postnote):
        assert len(postnote) != 0, ERROR_MSG
        return postnote

    @validates('myuser')
    def validate_myuser(self, key, myuser):
        assert myuser != '', ERROR_MSG
        assert myuser != None, 'None Value in fields are not allowed'
        return myuser
  
    def __repr__(self):
        return '<Note: %r>' % (self.postnote)
        
    @property
    def datetimeformat(self):
        return dump_datetime(self.datetime)
  
    @property
    def serialize(self):
        """
        Return object data in without messing it's order serializeable format
        
        to make this work, default Flask serialize JSON is changed through
        
        app.config["JSON_SORT_KEYS"] = False 
    
        """
        
        return OrderedDict([('postnote', self.postnote), \
                    ('date', dump_datetime(self.datetime))])

class Tag(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    entertag = db.Column(db.String(20))
    note_id = db.Column(db.Integer, db.ForeignKey('note.id'))   
    
    mytagnote = db.relationship('Note', back_populates='mytags')
  
    def __init__(self, entertag, mytagnote):
        self.entertag = entertag
        self.mytagnote = mytagnote
    
    def __repr__(self):
        return '<Note: %r>' % (self.entertag) 
       
        
    

        
        
    
    
      
    
    

sparrote/users/models.py
from sparrote import db
from sparrote.users import constants as USER
from sqlalchemy.orm import validates

ERROR_MSG = 'Empty fields are not allowed'

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(13), nullable=False)
    #role = db.Column(db.SmallInteger, default=USER.USER)
    #status = db.Column(db.SmallInteger, default=USER.NEW)
    mynotes = db.relationship('Note', back_populates='myuser', cascade='save-update, merge, delete')
    
    def __init__(self, name, email, password):
      self.name = name
      self.email = email
      self.password = password

    @validates('name')
    def validate_name(self, key, name):
      assert len(name) != 0, ERROR_MSG
      return name

    @validates('email')
    def validate_email(self, key, email):
      assert len(email) != 0, ERROR_MSG
      return email
  
    @validates('password')
    def validate_password(self, key, password):
      if not len(password):
        assert len(password) != 0, ERROR_MSG
        return password
      else:
        assert len(password) > 5, 'Password should be more than 5 characters long'
        return password
        
    """ 
    def getStatus(self):
      return USER.STATUS[self.status]==

    def getRole(self):
      return USER.ROLE[self.role]

    """ 


    def __repr__(self):
        return '<User %r>' % (self.name)
    

      

sparrote/notes/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, TextAreaField
from wtforms.validators import Required

class NoteForm(Form):
    postnote = TextAreaField('Post Note', validators=[Required()])
    entertag = TextField('Tag')

class SearchForm(Form):
	search_note = TextField('Search Note', validators=[Required()])

class AutoForm(Form):
    autocomp= TextField('autocomp',id='autocomplete')	

sparrote/users/forms.py
from flask.ext.wtf import Form, RecaptchaField
from wtforms import TextField, PasswordField, BooleanField, ValidationError
from wtforms.validators import Required, EqualTo, Email

from .models import User

def unique_entry_check(form, field):
  check = User.query.filter(User.email==form.email.data).first()
  if check:
    raise ValidationError('Email already registered')

class LoginForm(Form):
  email = TextField('Email address', [Required(), Email()])
  password = PasswordField('Password', [Required()])

class RegisterForm(Form):
  name = TextField('NickName',[Required()])
  email = TextField('Email address', [Required(), Email(), unique_entry_check])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Repeat Password', [
      Required(),
      EqualTo('password', message='Passwords must match')
      ])

  #recaptcha = RecaptchaField()
class CheckForm(Form):
  name = TextField('NickName',[Required()])
  email = TextField('Email address', [Required(), Email(), unique_entry_check])
  password = PasswordField('Password', [Required()])
  confirm = PasswordField('Repeat Password', [
      Required(),
      EqualTo('password', message='Passwords must match')
      ])

class SearchForm(Form):
  searchnote = TextField('searchnote')  

sparrote/__init__.py
import os
import sys

from flask import Flask, render_template, redirect, url_for, request, g
from flask_sqlalchemy import SQLAlchemy

from flask_debugtoolbar import DebugToolbarExtension

app = Flask(__name__)

app.config.from_object('config.DevConfig')
#toolbar = DebugToolbarExtension(app)

db = SQLAlchemy(app)

from sparrote.users.models import User
from sparrote.notes.models import Note, Tag
from sparrote.users.forms import RegisterForm, LoginForm, CheckForm, SearchForm

from sqlalchemy import and_
from sqlalchemy import desc

SECRET_KEY = 'you-will-never-guess'

# By default Flask will serialize JSON objects 
# in a way that the keys are ordered    
# override the default behaviour by setting 
#app.config["JSON_SORT_KEYS"] = False

@app.route("/")
def home():
    return render_template('main.html', regform=RegisterForm(request.form), \
                            loginform=LoginForm(request.form))

@app.errorhandler(404)
def not_found(error):
    return render_template('404.html'), 404
    
@app.context_processor
def tag_processor():
    def request_notes(tag):
        same_tag_notes = Note.query.join(Tag) \
        .filter(and_(Note.myuser==g.user, Tag.entertag==tag))
        return same_tag_notes
    return dict(same_tag_notes = request_notes)

from sparrote.users.views import mod as usersModule
from sparrote.notes.views import mod as noteModule

app.register_blueprint(usersModule)
app.register_blueprint(noteModule)

# Later on you'll import the other blueprints the same way:
#from app.comments.views import mod as commentsModule
#from app.posts.views import mod as postsModule
#app.register_blueprint(commentsModule)
#app.register_blueprint(postsModule)

sparrote/notes/views.py
from flask import Blueprint, request, render_template, \
      flash, g, session, redirect, url_for, json, jsonify, Response

from sparrote import db, app
from sparrote.users.models import User
from sparrote.users.decorators import requires_login
from sparrote.users.views import logout
from sparrote.notes.models import Note, Tag
from sparrote.notes.forms import NoteForm, SearchForm, AutoForm
from sparrote.notes.helper import tagfilter, usertags, request_notes

from sqlalchemy import desc, and_

mod = Blueprint('notes', __name__, url_prefix='/notes')

@mod.before_request
def before_request():
  """
  pull user's profile from the database before every request are treated
  
  """
  g.user = None
  if 'user_id' in session:
    g.user = User.query.get(session['user_id'])

@mod.route('/post/', methods=['GET', 'POST'])
@requires_login
def post():
  """
  Post Note Form
  """
  form = NoteForm(request.form)
  searchform = SearchForm(request.form)

  """
  search_form = SearchForm(request.form)

  if search_form.validate_on_submit: 
    find = search_form.search_note.data 
    user = User.query.get(session['user_id'])
    found_notes = Note.query.join(User) \
          .filter(and_(Note.myuser==user, Note.postnote==find))
    return render_template("notes/check.html", found_notes=found_notes)     
  """

  if form.validate_on_submit():
    note = Note(postnote=form.postnote.data, myuser=g.user)
    collecttags = tagfilter(form.entertag.data)
    
    if (isinstance(collecttags, list)):
      for tag in collecttags:
        tag = Tag(entertag=tag, mytagnote=note)
        db.session.add(tag)
    else:
      tag = Tag(entertag=collecttags, mytagnote=note)
      db.session.add(tag) 
      
    db.session.add(note)
    db.session.commit()
    flash('Note saved')    
    return redirect(url_for('notes.post'))
  
  currentnotes = Note.query.filter(Note.myuser == g.user).order_by(desc(Note.id))
  return render_template("notes/post.html", form=form, \
          currentnotes=currentnotes, searchform=searchform, \
            username=g.user.name, usertags= usertags())

@mod.route('/showtags/', methods=['GET', 'POST'])        
@requires_login     
def show_tags():
  tags = Tag.query.join(Note).filter(Note.myuser==g.user)

  # Use set to avoid displaying same tag more than once.
  unique_tags = set()
  unique_tags.update((tag.entertag for tag in tags))
  return render_template("notes/tags.html", tags=unique_tags)

"""
@app.route('/tag')
def jquery_click_tag():
  clicked_tag = request.args.get('a', 0, type=str)
  return jsonify(result=[note.serialize for note in request_notes(clicked_tag)])
"""

@mod.route('/tags/<string:tag>/')
@requires_login
def same_tag_notes(tag):
  form = NoteForm(request.form)
  user = User.query.get(session['user_id'])
  same_tag_notes = Note.query.join(Tag).join(User) \
          .filter(and_(Note.myuser==user, Tag.entertag==tag))
          
  return render_template("notes/sametagnotes.html", tag=tag, form=form, \
        same_tag_notes=same_tag_notes, usertags=usertags())

@mod.route('/delete/<int:noteid>')
@requires_login
def delete_post(noteid):
  currentnote = Note.query.filter(and_(Note.myuser == g.user, \
    Note.id == noteid )).first() 

  db.session.delete(currentnote)
  return redirect(url_for('notes.post'))

@mod.route('/search/', methods=['GET', 'POST'])
@requires_login
def search():
  form = SearchForm(request.form)
  if request.method == 'POST':
    query = form.search_note.data
    #found_notes = Note.query.filter(Note.postnote==query)
    return redirect(url_for("notes.search_result", query=query))
  return render_template("notes/search_result.html", form=form) 

@mod.route('/final/<string:query>')
@requires_login
def search_result(query):
  user = User.query.get(session['user_id'])
  result = Note.query.join(User) \
        .filter(and_(Note.myuser==user, Note.postnote==query))
  return render_template("notes/search_result.html", result=list(result))   

"""
@mod.route('/autocomplete',methods=['POST', 'GET'])
def autocomplete():
  result=''
  if request.method=='POST':
    look = request.form['query']
    query = db_session.query(Note.postnote).filter(Note.postnote.like('%' + str(look) + '%'))
    results = [mv[0] for mv in query.all()]
  return json.dumps({"suggestions":result})
"""  

"""
@mod.route('/autocomplete/',methods=['GET'])
def autocomplete():
    search = request.args.get('term')
    app.logger.debug(search)
    return jsonify(json_list=NAMES)
"""

@mod.route('/autocomplete', methods=['GET'])
def autocomplete():
    search = request.args.get('q')
    query = db.session.query(Note.postnote).filter(Note.postnote.like('%' + str(search) + '%'))
    results = [mv[0] for mv in query.all()]
    return jsonify(matching_results=results)

@mod.route('/background_process')
@requires_login
def background_process():
  lang = request.args.get('proglang', 0, type=str)
  user = User.query.get(session['user_id'])
  check = Note.query.join(User).filter(and_(Note.myuser==user, Note.postnote==lang))
  res = [i.postnote for i in check]
  if len(res):
    return jsonify({'result': res})
  else:
    return jsonify({'result': 'Not found'})

"""
@mod.route('/background_process')
def background_process():
  try:
    lang = request.args.get('proglang', 0, type=str)
    if lang.lower() == 'python':
      return jsonify(result='You are wise')
    else:
      return jsonify(result='Try again.')
  except Exception as e:
    return str(e)
"""

@mod.route('/autosearch/',methods=['GET','POST'])
def autosearch():
    return render_template("notes/auto.html")

sparrote/users/views.py
from flask import Blueprint, request, render_template, \
          flash, g, session, redirect, url_for
from werkzeug import check_password_hash, generate_password_hash

from sparrote import db, app
from sparrote.users.forms import RegisterForm, LoginForm, SearchForm
from sparrote.users.models import User
from sparrote.users.decorators import requires_login
from sparrote.notes.models import Note

mod = Blueprint('users', __name__, url_prefix='/users')

@mod.route('/home/')
def home():
  return render_template("users/main.html")  

@mod.before_request
def before_request():
  """
  pull user's profile from the database before every request are treated
  """
  g.user = None
  if 'user_id' in session:
    g.user = User.query.get(session['user_id'])

@mod.route('/login/', methods=['GET', 'POST'])
def login():
  """
  Login form
  """
  form = LoginForm(request.form)
  # make sure data are valid, but doesn't validate password is right
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    # we use werzeug to validate user's password
    if user and check_password_hash(user.password, form.password.data):
      # the session can't be modified as it's signed, 
      # it's a safe place to store the user id
      session['user_id'] = user.id
      #flash('Welcome %s' % user.name)
      return redirect(url_for('notes.post'))
    flash('Wrong email or password', 'error-message')
  return render_template("users/login.html", form=form)

@mod.route('/register/', methods=['GET', 'POST'])
def register():
  """
  Registration Form
  """
  form = RegisterForm(request.form)
  if form.validate_on_submit():

    #check for unique entry
    user_email = form.email.data
    check = User.query.filter(User.email==user_email).first()
  
    # create an user instance not yet stored in the database
    user = User(name=form.name.data, email=form.email.data, \
      password=generate_password_hash(form.password.data))

    db.session.add(user)
    db.session.commit()

    # Log the user in, as he now has an id
    session['user_id'] = user.id

    # flash will display a message to the user
    flash('Thanks for registering')
    # redirect user to the 'home' method of the user module.
    return redirect(url_for('notes.post'))
  return render_template("users/register.html", form=form)

@mod.route('/logout/')
@requires_login
def logout():
  """
  User logout
  
  """
  session.pop('user_id')
  flash('You were logged out')
  return redirect('/')

sparrote/templates/base.html
<html>  <head>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="/static/css/bootstrap-theme.min.css" rel="stylesheet" media="screen">
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab' rel='stylesheet' type='text/css'>
    <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
    <link rel=stylesheet type=text/css href="/static/css/main.css">
    {% endblock %}
    <title>{% block title %}Sparrote{% endblock %}</title>

    {% block head %} {% endblock %}

  </head>
  <body>
    <div id="header">{% block header %}{% endblock %}</div>
    <!--
    <div id="messages-wrap">
      <div id="messages">
        {% for category, msg in get_flashed_messages(with_categories=true) %}
          <p class="message flash-{{ category }}">{{ msg }}</p>
        {% endfor %}
      </div>
    </div>
    -->
    <div id="content">{% block content %}{% endblock %}</div>
    <div id="footer">{% block footer %}{% endblock %}</div>
  </body>
</html>

sparrote/templates/layout.html
<!doctype html>
<title>jQuery Example</title>
<script type="text/javascript"
src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript">
var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
</script>
{% block body %}{% endblock %}

sparrote/templates/main.html
{% extends "base.html" %}
{% block content %}

{% block style %} 
 <style>
  #custommaincontainer {
   margin-top: 150px;
  }
 </style>
{% endblock %}

<!-- form modification -->
<div class="container" id="custommaincontainer">
 
 <!-- login form-->
 <section>
  <div class="row">
   <div class="col-sm-6">
     <form method="POST" action="{{ url_for('users.login') }}" class="form-horizontal">
        
        {{ loginform.csrf_token }}
      
      <div class="form-group">
      {{ loginform.email.label(class="col-sm-4 col-md-4 control-label") }} 
       <div class="col-sm-8 col-md-7">
       {{ loginform.email(class="form-control", id="log-emailaddr" ) }}
       </div>
      </div>
      
      <div class="form-group">
       {{ loginform.password.label(class="col-sm-4 col-md-4 control-label") }} 
        <div class="col-sm-8 col-md-7">
       {{ loginform.password(class="form-control", id="log-pass") }} 
        </div>
      </div>
      
     <div class="form-group">
       <div class="col-sm-offset-4 col-sm-4">
        <input type="submit" value="Login" class="btn btn-default log-submit">
       </div>
     </div>
     
    </form>
   </div>
  </div><!--end row-->
 </section>
 
 <!-- end login form -->
 <hr>
 <!-- registration form -->
  <section>
  <div class="row">
   <div class="col-sm-6">
     <form method="POST" action="{{ url_for('users.register') }}" class="form-horizontal">
       
       {{ regform.csrf_token }}
      
      <div class="form-group">
      {{ regform.name.label(class="col-sm-4 col-md-4 control-label") }} 
        <div class="col-sm-8 col-md-7">
       {{ regform.name(class="form-control", id="username") }}
       </div>
      </div>
      
      <div class="form-group">
       {{ regform.email.label(class="col-sm-4 col-md-4 control-label") }} 
        <div class="col-sm-8 col-md-7">
       {{ regform.email(class="form-control", id="reg-email-addr") }} 
        </div>
      </div>
      
      <div class="form-group">
      {{ regform.password.label(class="col-sm-4 col-md-4 control-label") }} 
        <div class="col-sm-8 col-md-7">
       {{ regform.password(class="form-control", id="reg-pass") }}
       </div>
      </div>
      
      <div class="form-group">
       {{ regform.confirm.label(class="col-sm-4 col-md-4 control-label") }} 
         <div class="col-sm-8 col-md-7">
       {{ regform.confirm(class="form-control", id="repeat-pass") }} 
        </div>
      </div>
      
     <div class="form-group">
       <div class="col-sm-offset-4 col-sm-4">
        <input type="submit" value="Register" class="btn btn-default reg-submit">
       </div>
     </div>
     
    </form>
   </div>
  </div><!--end row-->
 </section>
 <!--end registration form -->
</div> <!-- end container -->


{% endblock %}